on:
  release:
    types: released

jobs:
  release_winget:
    name: Release Winget Package
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Dylibso.Extism.CLI
          installers-regex: '^extism-*-windows-amd64.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
