on:
  release:
    types: [created, edited]

permissions:
    contents: write
    packages: write

jobs:
  releases:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - run: |
       bash ./scripts/set-version.sh "${{ github.event.release.tag_name }}"
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./extism"
        binary_name: "extism"
        extra_files: LICENSE README.md
        release_tag: ${{ github.event.release.tag_name }}
        overwrite: true
